# Generated by Django 3.1.5 on 2021-01-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
