# Generated by Django 3.1.5 on 2021-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(),
        ),
    ]
