# Generated by Django 3.1.5 on 2021-01-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_option', models.IntegerField()),
                ('description_order', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.guestuser')),
            ],
        ),
    ]
