# Generated by Django 3.1.5 on 2021-01-11 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
        ('Menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_option', models.IntegerField()),
                ('description_order', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.guestuser')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menus.menu')),
            ],
        ),
    ]
