# Generated by Django 3.1.5 on 2021-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_order_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_option',
            field=models.CharField(max_length=6),
        ),
    ]
