# Generated by Django 3.1.5 on 2021-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20210111_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_option',
            field=models.IntegerField(),
        ),
    ]
